//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCMonitorClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PCMonitorClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member IC.
        /// </summary>
        internal static string combo1 {
            get {
                return ResourceManager.GetString("combo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string combo2 {
            get {
                return ResourceManager.GetString("combo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Usage:.
        /// </summary>
        internal static string cpuLabel {
            get {
                return ResourceManager.GetString("cpuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Usage:.
        /// </summary>
        internal static string diskLabel {
            get {
                return ResourceManager.GetString("diskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action for.
        /// </summary>
        internal static string idleAlert {
            get {
                return ResourceManager.GetString("idleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Time:.
        /// </summary>
        internal static string idleLabel {
            get {
                return ResourceManager.GetString("idleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number:.
        /// </summary>
        internal static string labelIDNum {
            get {
                return ResourceManager.GetString("labelIDNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type:.
        /// </summary>
        internal static string labelIDType {
            get {
                return ResourceManager.GetString("labelIDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership ID or IC:.
        /// </summary>
        internal static string labelMembershipId {
            get {
                return ResourceManager.GetString("labelMembershipId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string labelPassword {
            get {
                return ResourceManager.GetString("labelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahasa Melayu.
        /// </summary>
        internal static string langSelect {
            get {
                return ResourceManager.GetString("langSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginBtn {
            get {
                return ResourceManager.GetString("loginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        internal static string mins {
            get {
                return ResourceManager.GetString("mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed. Please try again!.
        /// </summary>
        internal static string msgFaild {
            get {
                return ResourceManager.GetString("msgFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use after.
        /// </summary>
        internal static string msgReady {
            get {
                return ResourceManager.GetString("msgReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful. Welcome to visit!.
        /// </summary>
        internal static string msgSuccess {
            get {
                return ResourceManager.GetString("msgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Usage:.
        /// </summary>
        internal static string netLabel {
            get {
                return ResourceManager.GetString("netLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM Usage:.
        /// </summary>
        internal static string ramLabel {
            get {
                return ResourceManager.GetString("ramLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain Time:.
        /// </summary>
        internal static string remainLabel {
            get {
                return ResourceManager.GetString("remainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Time:.
        /// </summary>
        internal static string sessionLabel {
            get {
                return ResourceManager.GetString("sessionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins left.
        /// </summary>
        internal static string timeAlert {
            get {
                return ResourceManager.GetString("timeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Client App.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
